version: "3.8"
services:
  airflow:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["bash","-lc","airflow standalone"]
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      # mount your repo's DAGs and data into the container
      - ../../airflow_dags:/opt/airflow/dags
      - ../../data:/opt/airflow/data
    ports:
      - "8080:8080"